const businessLA = [
  {
    name: 'Tocaya Organica',
    address: '12150 Millennium, #101',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90094',
    attributes: {
      Aura: 'exotic, touristy',
    },
    categories: 'Eating, Mexican, Restaurants, Organic',
  },
  {
    name: 'Raffaello Ristorante',
    address: '400 S Pacific Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90731',
    attributes: {
      Aura: 'romantic',
    },
    categories: 'Eating, Italian, Restaurants, Vegetarian-Friendly',
  },
  {
    name: 'Sushi Gen',
    address: '422 E 2nd St, Central Ave.',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90012',
    attributes: {
      Aura: 'exotic, peaceful',
    },
    categories: 'Eating, Japanese, Asian, Sushi, Restaurants',
  },
  {
    name: 'Madeo',
    address: '8897 Beverly Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90048',
    attributes: {
      Aura: 'romantic, upscale',
    },
    img:
      'https://cdn.vox-cdn.com/thumbor/JwfflVMxdLEIoXrMdsvOCRc-Mog=/0x0:2599x1354/1200x800/filters:focal(1093x470:1507x884)/cdn.vox-cdn.com/uploads/chorus_image/image/58942599/madeo_restaurant_google.0.png',
    categories: 'Eating, Dating, Italian, Restaurants, Vegetarian-Friendly, Vegan-Options, Upscale',
  },
  {
    name: 'Melody Bar and Grill',
    address: '9132 S Sepulveda Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90045',
    attributes: {
      Aura: 'lively, groovy',
    },
    categories: 'Drinking, Dating, Coffee, Bar, Pub, Cafe',
  },
  {
    name: 'Aroma Cafe',
    address: '4360 Tujunga Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '91604',
    attributes: {
      Aura: 'lively, romantic, hipster',
    },
    categories: 'Dating, Coffee, Tea, Bar, Pub, Cafe',
  },
  {
    name: 'Cafe Gratitude',
    address: '639 N Larchmont Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90004',
    attributes: {
      Aura: 'lively, romantic, imaginative',
    },
    categories: 'Dating, Coffee, Tea, Bar, Pub, Cafe, Vegetarian-Friendly, Vegan-Options',
  },
  {
    name: 'Javista Organic Coffee Bar',
    address: '6707 W Sunset Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90028',
    attributes: {
      Aura: 'romantic, hipster, imaginative',
    },
    img: 'https://s3-media1.fl.yelpcdn.com/bphoto/dbZ2-LzBc-VVTgM7J7djCQ/o.jpg',
    categories: 'Studying, Dating, Coffee, Tea, Organic, Bar, Pub, Cafe, Vegetarian-Friendly, Vegan-Options',
  },
  {
    name: 'Blu Jam Cafe',
    address: '15045 Ventura Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '91403',
    attributes: {
      Aura: 'groovy',
    },
    categories: 'Drinking, Coffee, Tea, Bar, Pub, Cafe, Vegetarian-Friendly, Vegan-Options',
  },
  {
    name: 'Cafe Intelligentsia',
    address: '1331 Abbot Kinney Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90291',
    attributes: {
      Aura: 'imaginative, romantic',
    },
    categories: 'Relaxing, Studying, Coffee, Tea, Bar, Pub, Cafe, Breakfast',
  },
  {
    name: 'Angel City Brewery',
    address: '216 S Alameda St',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90012',
    attributes: {
      Aura: 'lively, silly',
    },
    img: 'https://floridabeerblog.files.wordpress.com/2016/09/wp-1474495706370.jpg',
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Club',
  },
  {
    name: 'No Vacancy',
    address: '1727 N Hudson Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90028',
    attributes: {
      Aura: 'lively, groovy',
    },
    img: 'https://assets3.thrillist.com/v1/image/1616705/size/tmg-slideshow_l.jpg',
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Club',
  },
  {
    name: "Mondrian's Skybar",
    address: '8440 W Sunset Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90069',
    attributes: {
      Aura: 'lively, groovy',
    },
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Club',
  },
  {
    name: 'The Federal',
    address: '5303 Lankershim Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '91601',
    attributes: {
      Aura: 'peaceful, hipster',
    },
    img: 'http://nh.thefederalbar.com/wp-content/gallery/federal/MG_2043-edited-72.jpg',
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Club',
  },
  {
    name: 'Seven Bar Lounge',
    address: '555 W 7th St',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90014',
    attributes: {
      Aura: 'romantic, peaceful',
    },
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Upscale, Club',
  },
  {
    name: "Boardner's",
    address: '1652 N Cherokee Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90028',
    attributes: {
      Aura: 'lively, groovy, exotic',
    },
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Club, Shows',
  },
  {
    name: 'Black Rabbit Hose',
    address: '1719 N Hudson Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90028',
    attributes: {
      Aura: 'romantic, silly',
    },
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Club, Shows',
  },
  {
    name: 'The Rooftop at the Standard  Downtown LA',
    address: '550 S Flower St',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90071',
    attributes: {
      Aura: 'romantic, groovy',
    },
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Music',
  },
  {
    name: 'Howl at the Moon',
    address: '100 Universal City Plaza',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '91608',
    attributes: {
      Aura: 'lively, silly, groovy',
    },
    categories: 'Drinking, Nightlife, Food & Drink, Pub, Bar, Music',
  },
  {
    name: "4Play The Gentleman's Club",
    address: '2238 Cortner Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90064',
    attributes: {
      Aura: 'lively, touristy, romantic',
    },
    categories: 'Drinking, Nightlife, Nightclub, Upscale, Adult Entertainment, Strip Club',
  },
  {
    name: "Spearmint Rhino Gentlemen's Club Los Angeles",
    address: '2020 E Olympic Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90021',
    attributes: {
      Aura: 'lively, touristy, romantic',
    },
    categories: 'Drinking, Nightlife, Nightclub, Adult Entertainment, Strip Club',
  },
  {
    name: "Synn Gentlemen's Club",
    address: '365 N La Cienega Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90048',
    attributes: {
      Aura: 'lively, exotic',
    },
    categories: 'Drinking, Nightlife, Nightclub, Adult Entertainment, Strip Club',
  },
  {
    name: 'The Playpen',
    address: '1109 S Santa Fe Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90021',
    attributes: {
      Aura: 'lively, exotic',
    },
    categories: 'Drinking, Nightlife, Nightclub, Adult Entertainment, Strip Club',
  },
  {
    name: 'Blue Whale',
    address: '123 Astronaut E S Onizuka St Ste 301',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90012',
    attributes: {
      Aura: 'romantic, groovy',
    },
    categories: 'Drinking, Nightlife, Concerts, Shows',
  },
  {
    name: 'Izakaya & Bar Fu-ga',
    address: '111 S San Pedro St',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90012',
    attributes: {
      Aura: 'peaceful, exotic',
    },
    categories: 'Drinking, Relaxing, Nightlife, Restaurants, Food & Drink, Bar, Club, Japanese, Asian',
  },
  {
    name: "The Cow's End Cafe",
    address: '34 Washington Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90292',
    attributes: {
      Aura: 'romantic, peaceful',
    },
    categories: 'Studying, Dating, Relaxing, Coffee, Tea, Cafe, Deli, Food & Drink',
  },
  {
    name: "Menotti's Coffee Shop",
    address: '56 Windward Ave',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90291',
    attributes: {
      Aura: 'groovy, hipster',
    },
    categories: 'Relaxing, Coffee, Tea, Cafe, Food & Drink',
  },
  {
    name: 'Rise N Grind',
    address: '6501 Hollywood Blvd',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90028',
    attributes: {
      Aura: 'imaginative, peaceful',
    },
    categories: 'Studying, Relaxing, Coffee, Tea, Cafe, Food & Drink, Vegetarian-Friendly, Vegan-Options',
  },
];

module.exports = businessLA;
